name = "cf-workers-telegram-bot-v3"
main = "packages/worker/src/index.ts"

workers_dev = true
compatibility_date = "2024-11-11"

[ai]
binding = "AI"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "llama3"
database_id = "58a401e7-b568-4f10-86b9-bca7094b65e8"

[[r2_buckets]]
binding = "R2"
bucket_name = "share1"
